### ISSUE TITLE
Adding grade and score to states/daily

### ISSUE THREAD

**Issue by jplecavalier** [COVID19Tracking/covid-tracking-api#11]
I'm wondering if it would be possible for you to add a `quality` field in the States info API reflecting the data quality grade. You obviously have the information somewhere since you present it in the Most Recent Data tab.

Thanks!

**Comment by webmasterkai** [comment]
Hi @jplecavalier! The data on our website is built entirely off the API. You can access the grading info via https://covidtracking.com/api/states or https://covidtracking.com/api/states.csv There is a `grade` and `score` field that will be useful to you. If you don't find what you need please reopen this issue. Thanks for using our data!

**Comment by jplecavalier** [comment]
@webmasterkai - I did not notice that the there was `grade` and `score` fields in the **States current** API since I need historical data, thus **States daily 4PM** API. I think that any information that could be pertinent for any of both APIs should be accessible through the **States info** API.

In other words, the data itself should be in the current snapshot or in the historical snapshot, but the metadata about states (including `grade` and `score`) should be in the **States info** API.

**Comment by webmasterkai** [comment]
The initial thinking with having it on /states is that the grade is tracked to the current data and doesn't reflect historical scores. I do think it's probably useful available on /states/info

Are you using CSV downloads or json feeds?

**Comment by jplecavalier** [comment]
@webmasterkai - I use the `states/daily` and `states/info` APIs in CSV format. Do you have the historical value of `grade` and `score` for each date? I'll agree with you, those values will clearly change in time, so adding them to `states/daily` and letting them in `states` as well is probably the best solution.

**Comment by Nosferican** [comment]
It would be great to have the `grade` exposed in the GraphQL API. We are currently having to merge the timeseries data with the state quality. I agree that the quality should be tied to the record and not the state as it is important to have it from a historical perspective.

**Comment by Nosferican** [comment]
I have a script to download all the versions of the table using the GitHub API. After joining all the tables I have constructed a table like the following (e.g., from MT)
```
timestamp           | grade
2020-03-20T19:51:00 | B
2020-03-21T03:40:00 | B
2020-03-21T03:40:00 | B
2020-03-21T20:15:00 | B
2020-03-21T20:15:00 | B
2020-03-22T06:28:00 | B
2020-03-22T20:45:00 | B
2020-03-23T06:03:00 | C
2020-03-23T20:57:00 | C
2020-03-24T02:30:00 | C
2020-03-24T15:39:00 | C
2020-03-24T18:46:00 | C
2020-03-25T16:52:00 | C
2020-03-25T16:52:00 | C
2020-03-25T16:52:00 | C
2020-03-26T03:26:00 | C
2020-03-26T20:29:00 | C
2020-03-27T02:57:00 | C
2020-03-27T14:02:00 | A
```
I would like to consult with y'all on how to best join the table with the time series data (fake data).
```
date     | dateChecked         | grade
20200327 | 2020-03-27T10:00:00 | C?
```
Since the quality of the jurisdiction reporting changed sometime during the observations, what data quality values should the observations in the period of uncertainty get?

Something to consider is whether we want to have the data quality missing for recent observations or have a best guess and update the data quality note afterwards.

Would anyone provide the coded quality checks retroactively (e.g., from the comments field deprecated for notes)? Otherwise, I plan on reporting missing for the time being.

**Comment by Nosferican** [comment]
@jplecavalier see https://github.com/COVID19Tracking/covid-tracking-data/issues/22 for a temporary solution. Would love to get it incorporated in the API.
